import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Human-readable document numbers (WO-000001, TR-000001, SO-000001).
 *
 * Generated by PostgreSQL sequences rather than `MAX(code) + 1` in JavaScript.
 * `nextval()` is atomic and never hands the same value to two sessions, so two
 * users creating a work order at the same instant cannot collide - which is
 * exactly the class of bug this whole application is being judged on.
 */
export class DocumentSequences1700000001000 implements MigrationInterface {
  name = 'DocumentSequences1700000001000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "work_order_seq" START WITH 1 INCREMENT BY 1`);
    await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "stock_transfer_seq" START WITH 1 INCREMENT BY 1`);
    await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "customer_order_seq" START WITH 1 INCREMENT BY 1`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP SEQUENCE IF EXISTS "customer_order_seq"`);
    await queryRunner.query(`DROP SEQUENCE IF EXISTS "stock_transfer_seq"`);
    await queryRunner.query(`DROP SEQUENCE IF EXISTS "work_order_seq"`);
  }
}
